import type { Metadata } from "next";

import "../globals.css";

import { Footer } from "@components/Footer";

export const metadata: Metadata = {
  title: "Elio Gerges - Blog Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased w-[100vw] min-h-[100%]"
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
